### ISSUE TITLE
使用 ::v-deep  会被误识别为无用的 css

### ISSUE THREAD

**Issue by xbzhang2020** [qiaokeli111/vue-clearcss#2]
使用 `::v-deep` 的 css 代码，会被误识别为无用代码，其实是有用到的，用于修改子组件的样式。

<img width="1032" alt="截屏2022-10-21 14 20 37" src="https://user-images.githubusercontent.com/39360445/197130794-85175c2b-33e9-499d-871b-b621462629b9.png">

请问如何避免误识别呢。

**Comment by qiaokeli111** [comment]
> 使用 `::v-deep` 的 css 代码，会被误识别为无用代码，其实是有用到的，用于修改子组件的样式。
> 
> <img alt="截屏2022-10-21 14 20 37" width="1032" src="https://user-images.githubusercontent.com/39360445/197130794-85175c2b-33e9-499d-871b-b621462629b9.png">
> 
> 请问如何避免误识别呢。

兄弟，可以参考文档末尾的忽略配置，如图使用方法
![image](https://user-images.githubusercontent.com/39187010/197200255-79bc45c0-d59e-4e98-b44b-cfd7159920e5.png)
