### ISSUE TITLE
vue 组件没有 template 时运行会报错

### ISSUE THREAD

**Issue by xbzhang2020** [qiaokeli111/vue-clearcss#3]
报错截图：
<img width="1007" alt="截屏2022-10-24 17 23 32" src="https://user-images.githubusercontent.com/39360445/197494210-e78cc00c-9bf2-4360-ba1d-9727e0012104.png">

已定位到问题所在地方：./node_modules/vue-clearcss/css/parsecss.js

<img width="1188" alt="截屏2022-10-24 17 24 16" src="https://user-images.githubusercontent.com/39360445/197495515-b3703cc7-0f12-4cab-b003-bcca53591219.png">

原因分析：vue 组件没有 template 时，此处的`res.template`为null，访问`res.template.content`会报错。应该要加个非空判断。

大佬，辛苦修复下，或者我给大佬提个PR也行。🙏

**Comment by qiaokeli111** [comment]
> 报错截图： <img alt="截屏2022-10-24 17 23 32" width="1007" src="https://user-images.githubusercontent.com/39360445/197494210-e78cc00c-9bf2-4360-ba1d-9727e0012104.png">
> 
> 已定位到问题所在地方：./node_modules/vue-clearcss/css/parsecss.js
> 
> <img alt="截屏2022-10-24 17 24 16" width="1188" src="https://user-images.githubusercontent.com/39360445/197495515-b3703cc7-0f12-4cab-b003-bcca53591219.png">
> 
> 原因分析：vue 组件没有 template 时，此处的`res.template`为null，访问`res.template.content`会报错。应该要加个非空判断。
> 
> 大佬，辛苦修复下，或者我给大佬提个PR也行。🙏

npm 更新版本了哈，真实的vue文件还能没有template吗，第一次遇到

**Comment by xbzhang2020** [comment]
感谢。有的，批量在项目里跑了下，有的组件没有 template，而是在 render  选项里渲染的。

**Comment by xbzhang2020** [comment]
> > 报错截图： <img alt="截屏2022-10-24 17 23 32" width="1007" src="https://user-images.githubusercontent.com/39360445/197494210-e78cc00c-9bf2-4360-ba1d-9727e0012104.png">
> > 已定位到问题所在地方：./node_modules/vue-clearcss/css/parsecss.js
> > <img alt="截屏2022-10-24 17 24 16" width="1188" src="https://user-images.githubusercontent.com/39360445/197495515-b3703cc7-0f12-4cab-b003-bcca53591219.png">
> > 原因分析：vue 组件没有 template 时，此处的`res.template`为null，访问`res.template.content`会报错。应该要加个非空判断。
> > 大佬，辛苦修复下，或者我给大佬提个PR也行。🙏
> 
> npm 更新版本了哈，真实的vue文件还能没有template吗，第一次遇到

使用 npm 下载 1.1.14 版本报错了，下不下来。辛苦看下。
```shell
npm i vue-clearcss@1.1.14
```
